name: qichat_ui_sdk_example
description: "Demo app for qichat_ui_sdk."
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.3
  flutter_smart_dialog: ^4.9.4
  window_manager: ^0.4.3
  webview_flutter: ^4.9.0
  webview_flutter_wkwebview: ^3.14.0
  package_info_plus: ^7.0.0
  url_launcher: ^6.2.0

  qichat_ui_sdk:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
